// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataInstalledAppsProtos.proto

package it.unibo.participact.domain.proto;

public final class DataInstalledAppsProtos {
  private DataInstalledAppsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataInstalledAppsProtoListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .proto.DataInstalledAppsProto list = 1;
    /**
     * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
     */
    java.util.List<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto> 
        getListList();
    /**
     * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
     */
    it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto getList(int index);
    /**
     * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
     */
    java.util.List<? extends it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
     */
    it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.DataInstalledAppsProtoList}
   */
  public static final class DataInstalledAppsProtoList extends
      com.google.protobuf.GeneratedMessage
      implements DataInstalledAppsProtoListOrBuilder {
    // Use DataInstalledAppsProtoList.newBuilder() to construct.
    private DataInstalledAppsProtoList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataInstalledAppsProtoList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataInstalledAppsProtoList defaultInstance;
    public static DataInstalledAppsProtoList getDefaultInstance() {
      return defaultInstance;
    }

    public DataInstalledAppsProtoList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataInstalledAppsProtoList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(input.readMessage(it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProtoList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProtoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList.class, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList.Builder.class);
    }

    public static com.google.protobuf.Parser<DataInstalledAppsProtoList> PARSER =
        new com.google.protobuf.AbstractParser<DataInstalledAppsProtoList>() {
      public DataInstalledAppsProtoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataInstalledAppsProtoList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataInstalledAppsProtoList> getParserForType() {
      return PARSER;
    }

    // repeated .proto.DataInstalledAppsProto list = 1;
    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto> list_;
    /**
     * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
     */
    public java.util.List<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto> getListList() {
      return list_;
    }
    /**
     * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
     */
    public java.util.List<? extends it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
     */
    public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
     */
    public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private void initFields() {
      list_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getListCount(); i++) {
        if (!getList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DataInstalledAppsProtoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProtoList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProtoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList.class, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList.Builder.class);
      }

      // Construct using it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProtoList_descriptor;
      }

      public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList getDefaultInstanceForType() {
        return it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList.getDefaultInstance();
      }

      public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList build() {
        it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList buildPartial() {
        it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList result = new it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList) {
          return mergeFrom((it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList other) {
        if (other == it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getListCount(); i++) {
          if (!getList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .proto.DataInstalledAppsProto list = 1;
      private java.util.List<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder> listBuilder_;

      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public java.util.List<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public Builder setList(
          int index, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public Builder setList(
          int index, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public Builder addList(it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public Builder addList(
          int index, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public Builder addList(
          it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public Builder addList(
          int index, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          super.addAll(values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public java.util.List<? extends it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.DataInstalledAppsProto list = 1;</code>
       */
      public java.util.List<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.DataInstalledAppsProtoList)
    }

    static {
      defaultInstance = new DataInstalledAppsProtoList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.DataInstalledAppsProtoList)
  }

  public interface DataInstalledAppsProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 sampleTime = 1;
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    boolean hasSampleTime();
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    long getSampleTime();

    // required string pkg_name = 2;
    /**
     * <code>required string pkg_name = 2;</code>
     */
    boolean hasPkgName();
    /**
     * <code>required string pkg_name = 2;</code>
     */
    java.lang.String getPkgName();
    /**
     * <code>required string pkg_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getPkgNameBytes();

    // required float version_code = 3;
    /**
     * <code>required float version_code = 3;</code>
     */
    boolean hasVersionCode();
    /**
     * <code>required float version_code = 3;</code>
     */
    float getVersionCode();

    // required string version_name = 4;
    /**
     * <code>required string version_name = 4;</code>
     */
    boolean hasVersionName();
    /**
     * <code>required string version_name = 4;</code>
     */
    java.lang.String getVersionName();
    /**
     * <code>required string version_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getVersionNameBytes();

    // required string requested_permissions = 5;
    /**
     * <code>required string requested_permissions = 5;</code>
     */
    boolean hasRequestedPermissions();
    /**
     * <code>required string requested_permissions = 5;</code>
     */
    java.lang.String getRequestedPermissions();
    /**
     * <code>required string requested_permissions = 5;</code>
     */
    com.google.protobuf.ByteString
        getRequestedPermissionsBytes();
  }
  /**
   * Protobuf type {@code proto.DataInstalledAppsProto}
   */
  public static final class DataInstalledAppsProto extends
      com.google.protobuf.GeneratedMessage
      implements DataInstalledAppsProtoOrBuilder {
    // Use DataInstalledAppsProto.newBuilder() to construct.
    private DataInstalledAppsProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataInstalledAppsProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataInstalledAppsProto defaultInstance;
    public static DataInstalledAppsProto getDefaultInstance() {
      return defaultInstance;
    }

    public DataInstalledAppsProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataInstalledAppsProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sampleTime_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              pkgName_ = input.readBytes();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              versionCode_ = input.readFloat();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              versionName_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              requestedPermissions_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.class, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder.class);
    }

    public static com.google.protobuf.Parser<DataInstalledAppsProto> PARSER =
        new com.google.protobuf.AbstractParser<DataInstalledAppsProto>() {
      public DataInstalledAppsProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataInstalledAppsProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataInstalledAppsProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 sampleTime = 1;
    public static final int SAMPLETIME_FIELD_NUMBER = 1;
    private long sampleTime_;
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    public boolean hasSampleTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    public long getSampleTime() {
      return sampleTime_;
    }

    // required string pkg_name = 2;
    public static final int PKG_NAME_FIELD_NUMBER = 2;
    private java.lang.Object pkgName_;
    /**
     * <code>required string pkg_name = 2;</code>
     */
    public boolean hasPkgName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string pkg_name = 2;</code>
     */
    public java.lang.String getPkgName() {
      java.lang.Object ref = pkgName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pkgName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string pkg_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPkgNameBytes() {
      java.lang.Object ref = pkgName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pkgName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required float version_code = 3;
    public static final int VERSION_CODE_FIELD_NUMBER = 3;
    private float versionCode_;
    /**
     * <code>required float version_code = 3;</code>
     */
    public boolean hasVersionCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float version_code = 3;</code>
     */
    public float getVersionCode() {
      return versionCode_;
    }

    // required string version_name = 4;
    public static final int VERSION_NAME_FIELD_NUMBER = 4;
    private java.lang.Object versionName_;
    /**
     * <code>required string version_name = 4;</code>
     */
    public boolean hasVersionName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string version_name = 4;</code>
     */
    public java.lang.String getVersionName() {
      java.lang.Object ref = versionName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          versionName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string version_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVersionNameBytes() {
      java.lang.Object ref = versionName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        versionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string requested_permissions = 5;
    public static final int REQUESTED_PERMISSIONS_FIELD_NUMBER = 5;
    private java.lang.Object requestedPermissions_;
    /**
     * <code>required string requested_permissions = 5;</code>
     */
    public boolean hasRequestedPermissions() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string requested_permissions = 5;</code>
     */
    public java.lang.String getRequestedPermissions() {
      java.lang.Object ref = requestedPermissions_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestedPermissions_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string requested_permissions = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRequestedPermissionsBytes() {
      java.lang.Object ref = requestedPermissions_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestedPermissions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sampleTime_ = 0L;
      pkgName_ = "";
      versionCode_ = 0F;
      versionName_ = "";
      requestedPermissions_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSampleTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPkgName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersionCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersionName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestedPermissions()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, sampleTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPkgNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, versionCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getVersionNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getRequestedPermissionsBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sampleTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPkgNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, versionCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getVersionNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getRequestedPermissionsBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DataInstalledAppsProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.class, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder.class);
      }

      // Construct using it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sampleTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        pkgName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        versionCode_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        versionName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        requestedPermissions_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProto_descriptor;
      }

      public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto getDefaultInstanceForType() {
        return it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.getDefaultInstance();
      }

      public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto build() {
        it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto buildPartial() {
        it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto result = new it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sampleTime_ = sampleTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pkgName_ = pkgName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.versionCode_ = versionCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.versionName_ = versionName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.requestedPermissions_ = requestedPermissions_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto) {
          return mergeFrom((it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto other) {
        if (other == it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.getDefaultInstance()) return this;
        if (other.hasSampleTime()) {
          setSampleTime(other.getSampleTime());
        }
        if (other.hasPkgName()) {
          bitField0_ |= 0x00000002;
          pkgName_ = other.pkgName_;
          onChanged();
        }
        if (other.hasVersionCode()) {
          setVersionCode(other.getVersionCode());
        }
        if (other.hasVersionName()) {
          bitField0_ |= 0x00000008;
          versionName_ = other.versionName_;
          onChanged();
        }
        if (other.hasRequestedPermissions()) {
          bitField0_ |= 0x00000010;
          requestedPermissions_ = other.requestedPermissions_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSampleTime()) {
          
          return false;
        }
        if (!hasPkgName()) {
          
          return false;
        }
        if (!hasVersionCode()) {
          
          return false;
        }
        if (!hasVersionName()) {
          
          return false;
        }
        if (!hasRequestedPermissions()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 sampleTime = 1;
      private long sampleTime_ ;
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public boolean hasSampleTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public long getSampleTime() {
        return sampleTime_;
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public Builder setSampleTime(long value) {
        bitField0_ |= 0x00000001;
        sampleTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public Builder clearSampleTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sampleTime_ = 0L;
        onChanged();
        return this;
      }

      // required string pkg_name = 2;
      private java.lang.Object pkgName_ = "";
      /**
       * <code>required string pkg_name = 2;</code>
       */
      public boolean hasPkgName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string pkg_name = 2;</code>
       */
      public java.lang.String getPkgName() {
        java.lang.Object ref = pkgName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pkgName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string pkg_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPkgNameBytes() {
        java.lang.Object ref = pkgName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pkgName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string pkg_name = 2;</code>
       */
      public Builder setPkgName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pkgName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string pkg_name = 2;</code>
       */
      public Builder clearPkgName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pkgName_ = getDefaultInstance().getPkgName();
        onChanged();
        return this;
      }
      /**
       * <code>required string pkg_name = 2;</code>
       */
      public Builder setPkgNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pkgName_ = value;
        onChanged();
        return this;
      }

      // required float version_code = 3;
      private float versionCode_ ;
      /**
       * <code>required float version_code = 3;</code>
       */
      public boolean hasVersionCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float version_code = 3;</code>
       */
      public float getVersionCode() {
        return versionCode_;
      }
      /**
       * <code>required float version_code = 3;</code>
       */
      public Builder setVersionCode(float value) {
        bitField0_ |= 0x00000004;
        versionCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float version_code = 3;</code>
       */
      public Builder clearVersionCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        versionCode_ = 0F;
        onChanged();
        return this;
      }

      // required string version_name = 4;
      private java.lang.Object versionName_ = "";
      /**
       * <code>required string version_name = 4;</code>
       */
      public boolean hasVersionName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string version_name = 4;</code>
       */
      public java.lang.String getVersionName() {
        java.lang.Object ref = versionName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          versionName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string version_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getVersionNameBytes() {
        java.lang.Object ref = versionName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          versionName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string version_name = 4;</code>
       */
      public Builder setVersionName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        versionName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string version_name = 4;</code>
       */
      public Builder clearVersionName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        versionName_ = getDefaultInstance().getVersionName();
        onChanged();
        return this;
      }
      /**
       * <code>required string version_name = 4;</code>
       */
      public Builder setVersionNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        versionName_ = value;
        onChanged();
        return this;
      }

      // required string requested_permissions = 5;
      private java.lang.Object requestedPermissions_ = "";
      /**
       * <code>required string requested_permissions = 5;</code>
       */
      public boolean hasRequestedPermissions() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string requested_permissions = 5;</code>
       */
      public java.lang.String getRequestedPermissions() {
        java.lang.Object ref = requestedPermissions_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestedPermissions_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string requested_permissions = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRequestedPermissionsBytes() {
        java.lang.Object ref = requestedPermissions_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestedPermissions_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string requested_permissions = 5;</code>
       */
      public Builder setRequestedPermissions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        requestedPermissions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string requested_permissions = 5;</code>
       */
      public Builder clearRequestedPermissions() {
        bitField0_ = (bitField0_ & ~0x00000010);
        requestedPermissions_ = getDefaultInstance().getRequestedPermissions();
        onChanged();
        return this;
      }
      /**
       * <code>required string requested_permissions = 5;</code>
       */
      public Builder setRequestedPermissionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        requestedPermissions_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.DataInstalledAppsProto)
    }

    static {
      defaultInstance = new DataInstalledAppsProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.DataInstalledAppsProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DataInstalledAppsProtoList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_DataInstalledAppsProtoList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DataInstalledAppsProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_DataInstalledAppsProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035DataInstalledAppsProtos.proto\022\005proto\"I" +
      "\n\032DataInstalledAppsProtoList\022+\n\004list\030\001 \003" +
      "(\0132\035.proto.DataInstalledAppsProto\"\211\001\n\026Da" +
      "taInstalledAppsProto\022\022\n\nsampleTime\030\001 \002(\003" +
      "\022\020\n\010pkg_name\030\002 \002(\t\022\024\n\014version_code\030\003 \002(\002" +
      "\022\024\n\014version_name\030\004 \002(\t\022\035\n\025requested_perm" +
      "issions\030\005 \002(\tB<\n!it.unibo.participact.do" +
      "main.protoB\027DataInstalledAppsProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_DataInstalledAppsProtoList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_DataInstalledAppsProtoList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_DataInstalledAppsProtoList_descriptor,
              new java.lang.String[] { "List", });
          internal_static_proto_DataInstalledAppsProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_DataInstalledAppsProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_DataInstalledAppsProto_descriptor,
              new java.lang.String[] { "SampleTime", "PkgName", "VersionCode", "VersionName", "RequestedPermissions", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
