// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataAppOnScreenProtos.proto

package it.unibo.participact.domain.proto;

public final class DataAppOnScreenProtos {
  private DataAppOnScreenProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataAppOnScreenProtoListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .proto.DataAppOnScreenProto list = 1;
    /**
     * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
     */
    java.util.List<it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto> 
        getListList();
    /**
     * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
     */
    it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto getList(int index);
    /**
     * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
     */
    java.util.List<? extends it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
     */
    it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.DataAppOnScreenProtoList}
   */
  public static final class DataAppOnScreenProtoList extends
      com.google.protobuf.GeneratedMessage
      implements DataAppOnScreenProtoListOrBuilder {
    // Use DataAppOnScreenProtoList.newBuilder() to construct.
    private DataAppOnScreenProtoList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataAppOnScreenProtoList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataAppOnScreenProtoList defaultInstance;
    public static DataAppOnScreenProtoList getDefaultInstance() {
      return defaultInstance;
    }

    public DataAppOnScreenProtoList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataAppOnScreenProtoList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(input.readMessage(it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.unibo.participact.domain.proto.DataAppOnScreenProtos.internal_static_proto_DataAppOnScreenProtoList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.unibo.participact.domain.proto.DataAppOnScreenProtos.internal_static_proto_DataAppOnScreenProtoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList.class, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList.Builder.class);
    }

    public static com.google.protobuf.Parser<DataAppOnScreenProtoList> PARSER =
        new com.google.protobuf.AbstractParser<DataAppOnScreenProtoList>() {
      public DataAppOnScreenProtoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataAppOnScreenProtoList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataAppOnScreenProtoList> getParserForType() {
      return PARSER;
    }

    // repeated .proto.DataAppOnScreenProto list = 1;
    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto> list_;
    /**
     * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
     */
    public java.util.List<it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto> getListList() {
      return list_;
    }
    /**
     * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
     */
    public java.util.List<? extends it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
     */
    public it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
     */
    public it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private void initFields() {
      list_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getListCount(); i++) {
        if (!getList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DataAppOnScreenProtoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.unibo.participact.domain.proto.DataAppOnScreenProtos.internal_static_proto_DataAppOnScreenProtoList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.unibo.participact.domain.proto.DataAppOnScreenProtos.internal_static_proto_DataAppOnScreenProtoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList.class, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList.Builder.class);
      }

      // Construct using it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.unibo.participact.domain.proto.DataAppOnScreenProtos.internal_static_proto_DataAppOnScreenProtoList_descriptor;
      }

      public it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList getDefaultInstanceForType() {
        return it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList.getDefaultInstance();
      }

      public it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList build() {
        it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList buildPartial() {
        it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList result = new it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList) {
          return mergeFrom((it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList other) {
        if (other == it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getListCount(); i++) {
          if (!getList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .proto.DataAppOnScreenProto list = 1;
      private java.util.List<it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.Builder, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoOrBuilder> listBuilder_;

      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public java.util.List<it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public Builder setList(
          int index, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public Builder setList(
          int index, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public Builder addList(it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public Builder addList(
          int index, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public Builder addList(
          it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public Builder addList(
          int index, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          super.addAll(values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public java.util.List<? extends it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.DataAppOnScreenProto list = 1;</code>
       */
      public java.util.List<it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.Builder, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.Builder, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.DataAppOnScreenProtoList)
    }

    static {
      defaultInstance = new DataAppOnScreenProtoList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.DataAppOnScreenProtoList)
  }

  public interface DataAppOnScreenProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 sampleTime = 1;
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    boolean hasSampleTime();
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    long getSampleTime();

    // required string appName = 2;
    /**
     * <code>required string appName = 2;</code>
     */
    boolean hasAppName();
    /**
     * <code>required string appName = 2;</code>
     */
    java.lang.String getAppName();
    /**
     * <code>required string appName = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppNameBytes();

    // required int64 startTime = 3;
    /**
     * <code>required int64 startTime = 3;</code>
     */
    boolean hasStartTime();
    /**
     * <code>required int64 startTime = 3;</code>
     */
    long getStartTime();

    // required int64 endTime = 4;
    /**
     * <code>required int64 endTime = 4;</code>
     */
    boolean hasEndTime();
    /**
     * <code>required int64 endTime = 4;</code>
     */
    long getEndTime();
  }
  /**
   * Protobuf type {@code proto.DataAppOnScreenProto}
   */
  public static final class DataAppOnScreenProto extends
      com.google.protobuf.GeneratedMessage
      implements DataAppOnScreenProtoOrBuilder {
    // Use DataAppOnScreenProto.newBuilder() to construct.
    private DataAppOnScreenProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataAppOnScreenProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataAppOnScreenProto defaultInstance;
    public static DataAppOnScreenProto getDefaultInstance() {
      return defaultInstance;
    }

    public DataAppOnScreenProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataAppOnScreenProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sampleTime_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              appName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              startTime_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              endTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.unibo.participact.domain.proto.DataAppOnScreenProtos.internal_static_proto_DataAppOnScreenProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.unibo.participact.domain.proto.DataAppOnScreenProtos.internal_static_proto_DataAppOnScreenProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.class, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.Builder.class);
    }

    public static com.google.protobuf.Parser<DataAppOnScreenProto> PARSER =
        new com.google.protobuf.AbstractParser<DataAppOnScreenProto>() {
      public DataAppOnScreenProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataAppOnScreenProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataAppOnScreenProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 sampleTime = 1;
    public static final int SAMPLETIME_FIELD_NUMBER = 1;
    private long sampleTime_;
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    public boolean hasSampleTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    public long getSampleTime() {
      return sampleTime_;
    }

    // required string appName = 2;
    public static final int APPNAME_FIELD_NUMBER = 2;
    private java.lang.Object appName_;
    /**
     * <code>required string appName = 2;</code>
     */
    public boolean hasAppName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string appName = 2;</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string appName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 startTime = 3;
    public static final int STARTTIME_FIELD_NUMBER = 3;
    private long startTime_;
    /**
     * <code>required int64 startTime = 3;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 startTime = 3;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    // required int64 endTime = 4;
    public static final int ENDTIME_FIELD_NUMBER = 4;
    private long endTime_;
    /**
     * <code>required int64 endTime = 4;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 endTime = 4;</code>
     */
    public long getEndTime() {
      return endTime_;
    }

    private void initFields() {
      sampleTime_ = 0L;
      appName_ = "";
      startTime_ = 0L;
      endTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSampleTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, sampleTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAppNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, startTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, endTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sampleTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAppNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, startTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, endTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DataAppOnScreenProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.unibo.participact.domain.proto.DataAppOnScreenProtos.internal_static_proto_DataAppOnScreenProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.unibo.participact.domain.proto.DataAppOnScreenProtos.internal_static_proto_DataAppOnScreenProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.class, it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.Builder.class);
      }

      // Construct using it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sampleTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        appName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        startTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.unibo.participact.domain.proto.DataAppOnScreenProtos.internal_static_proto_DataAppOnScreenProto_descriptor;
      }

      public it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto getDefaultInstanceForType() {
        return it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.getDefaultInstance();
      }

      public it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto build() {
        it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto buildPartial() {
        it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto result = new it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sampleTime_ = sampleTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appName_ = appName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.endTime_ = endTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto) {
          return mergeFrom((it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto other) {
        if (other == it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto.getDefaultInstance()) return this;
        if (other.hasSampleTime()) {
          setSampleTime(other.getSampleTime());
        }
        if (other.hasAppName()) {
          bitField0_ |= 0x00000002;
          appName_ = other.appName_;
          onChanged();
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSampleTime()) {
          
          return false;
        }
        if (!hasAppName()) {
          
          return false;
        }
        if (!hasStartTime()) {
          
          return false;
        }
        if (!hasEndTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.unibo.participact.domain.proto.DataAppOnScreenProtos.DataAppOnScreenProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 sampleTime = 1;
      private long sampleTime_ ;
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public boolean hasSampleTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public long getSampleTime() {
        return sampleTime_;
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public Builder setSampleTime(long value) {
        bitField0_ |= 0x00000001;
        sampleTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public Builder clearSampleTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sampleTime_ = 0L;
        onChanged();
        return this;
      }

      // required string appName = 2;
      private java.lang.Object appName_ = "";
      /**
       * <code>required string appName = 2;</code>
       */
      public boolean hasAppName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string appName = 2;</code>
       */
      public java.lang.String getAppName() {
        java.lang.Object ref = appName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          appName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string appName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        java.lang.Object ref = appName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string appName = 2;</code>
       */
      public Builder setAppName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string appName = 2;</code>
       */
      public Builder clearAppName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appName_ = getDefaultInstance().getAppName();
        onChanged();
        return this;
      }
      /**
       * <code>required string appName = 2;</code>
       */
      public Builder setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appName_ = value;
        onChanged();
        return this;
      }

      // required int64 startTime = 3;
      private long startTime_ ;
      /**
       * <code>required int64 startTime = 3;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 startTime = 3;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>required int64 startTime = 3;</code>
       */
      public Builder setStartTime(long value) {
        bitField0_ |= 0x00000004;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 startTime = 3;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      // required int64 endTime = 4;
      private long endTime_ ;
      /**
       * <code>required int64 endTime = 4;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 endTime = 4;</code>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>required int64 endTime = 4;</code>
       */
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000008;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 endTime = 4;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        endTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.DataAppOnScreenProto)
    }

    static {
      defaultInstance = new DataAppOnScreenProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.DataAppOnScreenProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DataAppOnScreenProtoList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_DataAppOnScreenProtoList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DataAppOnScreenProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_DataAppOnScreenProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033DataAppOnScreenProtos.proto\022\005proto\"E\n\030" +
      "DataAppOnScreenProtoList\022)\n\004list\030\001 \003(\0132\033" +
      ".proto.DataAppOnScreenProto\"_\n\024DataAppOn" +
      "ScreenProto\022\022\n\nsampleTime\030\001 \002(\003\022\017\n\007appNa" +
      "me\030\002 \002(\t\022\021\n\tstartTime\030\003 \002(\003\022\017\n\007endTime\030\004" +
      " \002(\003B:\n!it.unibo.participact.domain.prot" +
      "oB\025DataAppOnScreenProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_DataAppOnScreenProtoList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_DataAppOnScreenProtoList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_DataAppOnScreenProtoList_descriptor,
              new java.lang.String[] { "List", });
          internal_static_proto_DataAppOnScreenProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_DataAppOnScreenProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_DataAppOnScreenProto_descriptor,
              new java.lang.String[] { "SampleTime", "AppName", "StartTime", "EndTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
