// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataGyroscopeProtos.proto

package it.unibo.participact.domain.proto;

public final class DataGyroscopeProtos {
  private DataGyroscopeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataGyroscopeProtoListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .proto.DataGyroscopeProto list = 1;
    /**
     * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
     */
    java.util.List<it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto> 
        getListList();
    /**
     * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
     */
    it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto getList(int index);
    /**
     * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
     */
    java.util.List<? extends it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
     */
    it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.DataGyroscopeProtoList}
   */
  public static final class DataGyroscopeProtoList extends
      com.google.protobuf.GeneratedMessage
      implements DataGyroscopeProtoListOrBuilder {
    // Use DataGyroscopeProtoList.newBuilder() to construct.
    private DataGyroscopeProtoList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataGyroscopeProtoList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataGyroscopeProtoList defaultInstance;
    public static DataGyroscopeProtoList getDefaultInstance() {
      return defaultInstance;
    }

    public DataGyroscopeProtoList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataGyroscopeProtoList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(input.readMessage(it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.unibo.participact.domain.proto.DataGyroscopeProtos.internal_static_proto_DataGyroscopeProtoList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.unibo.participact.domain.proto.DataGyroscopeProtos.internal_static_proto_DataGyroscopeProtoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList.class, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList.Builder.class);
    }

    public static com.google.protobuf.Parser<DataGyroscopeProtoList> PARSER =
        new com.google.protobuf.AbstractParser<DataGyroscopeProtoList>() {
      public DataGyroscopeProtoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataGyroscopeProtoList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataGyroscopeProtoList> getParserForType() {
      return PARSER;
    }

    // repeated .proto.DataGyroscopeProto list = 1;
    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto> list_;
    /**
     * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
     */
    public java.util.List<it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto> getListList() {
      return list_;
    }
    /**
     * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
     */
    public java.util.List<? extends it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
     */
    public it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
     */
    public it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private void initFields() {
      list_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getListCount(); i++) {
        if (!getList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DataGyroscopeProtoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.unibo.participact.domain.proto.DataGyroscopeProtos.internal_static_proto_DataGyroscopeProtoList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.unibo.participact.domain.proto.DataGyroscopeProtos.internal_static_proto_DataGyroscopeProtoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList.class, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList.Builder.class);
      }

      // Construct using it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.unibo.participact.domain.proto.DataGyroscopeProtos.internal_static_proto_DataGyroscopeProtoList_descriptor;
      }

      public it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList getDefaultInstanceForType() {
        return it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList.getDefaultInstance();
      }

      public it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList build() {
        it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList buildPartial() {
        it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList result = new it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList) {
          return mergeFrom((it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList other) {
        if (other == it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getListCount(); i++) {
          if (!getList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .proto.DataGyroscopeProto list = 1;
      private java.util.List<it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.Builder, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoOrBuilder> listBuilder_;

      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public java.util.List<it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public Builder setList(
          int index, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public Builder setList(
          int index, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public Builder addList(it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public Builder addList(
          int index, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public Builder addList(
          it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public Builder addList(
          int index, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          super.addAll(values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public java.util.List<? extends it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.DataGyroscopeProto list = 1;</code>
       */
      public java.util.List<it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.Builder, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.Builder, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.DataGyroscopeProtoList)
    }

    static {
      defaultInstance = new DataGyroscopeProtoList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.DataGyroscopeProtoList)
  }

  public interface DataGyroscopeProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 sampleTime = 1;
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    boolean hasSampleTime();
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    long getSampleTime();

    // required float rotation_x = 2;
    /**
     * <code>required float rotation_x = 2;</code>
     */
    boolean hasRotationX();
    /**
     * <code>required float rotation_x = 2;</code>
     */
    float getRotationX();

    // required float rotation_y = 3;
    /**
     * <code>required float rotation_y = 3;</code>
     */
    boolean hasRotationY();
    /**
     * <code>required float rotation_y = 3;</code>
     */
    float getRotationY();

    // required float rotation_z = 4;
    /**
     * <code>required float rotation_z = 4;</code>
     */
    boolean hasRotationZ();
    /**
     * <code>required float rotation_z = 4;</code>
     */
    float getRotationZ();
  }
  /**
   * Protobuf type {@code proto.DataGyroscopeProto}
   */
  public static final class DataGyroscopeProto extends
      com.google.protobuf.GeneratedMessage
      implements DataGyroscopeProtoOrBuilder {
    // Use DataGyroscopeProto.newBuilder() to construct.
    private DataGyroscopeProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataGyroscopeProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataGyroscopeProto defaultInstance;
    public static DataGyroscopeProto getDefaultInstance() {
      return defaultInstance;
    }

    public DataGyroscopeProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataGyroscopeProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sampleTime_ = input.readInt64();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              rotationX_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              rotationY_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              rotationZ_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.unibo.participact.domain.proto.DataGyroscopeProtos.internal_static_proto_DataGyroscopeProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.unibo.participact.domain.proto.DataGyroscopeProtos.internal_static_proto_DataGyroscopeProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.class, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.Builder.class);
    }

    public static com.google.protobuf.Parser<DataGyroscopeProto> PARSER =
        new com.google.protobuf.AbstractParser<DataGyroscopeProto>() {
      public DataGyroscopeProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataGyroscopeProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataGyroscopeProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 sampleTime = 1;
    public static final int SAMPLETIME_FIELD_NUMBER = 1;
    private long sampleTime_;
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    public boolean hasSampleTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    public long getSampleTime() {
      return sampleTime_;
    }

    // required float rotation_x = 2;
    public static final int ROTATION_X_FIELD_NUMBER = 2;
    private float rotationX_;
    /**
     * <code>required float rotation_x = 2;</code>
     */
    public boolean hasRotationX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float rotation_x = 2;</code>
     */
    public float getRotationX() {
      return rotationX_;
    }

    // required float rotation_y = 3;
    public static final int ROTATION_Y_FIELD_NUMBER = 3;
    private float rotationY_;
    /**
     * <code>required float rotation_y = 3;</code>
     */
    public boolean hasRotationY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float rotation_y = 3;</code>
     */
    public float getRotationY() {
      return rotationY_;
    }

    // required float rotation_z = 4;
    public static final int ROTATION_Z_FIELD_NUMBER = 4;
    private float rotationZ_;
    /**
     * <code>required float rotation_z = 4;</code>
     */
    public boolean hasRotationZ() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float rotation_z = 4;</code>
     */
    public float getRotationZ() {
      return rotationZ_;
    }

    private void initFields() {
      sampleTime_ = 0L;
      rotationX_ = 0F;
      rotationY_ = 0F;
      rotationZ_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSampleTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRotationX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRotationY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRotationZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, sampleTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, rotationX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, rotationY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, rotationZ_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sampleTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, rotationX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, rotationY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, rotationZ_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DataGyroscopeProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.unibo.participact.domain.proto.DataGyroscopeProtos.internal_static_proto_DataGyroscopeProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.unibo.participact.domain.proto.DataGyroscopeProtos.internal_static_proto_DataGyroscopeProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.class, it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.Builder.class);
      }

      // Construct using it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sampleTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        rotationX_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        rotationY_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        rotationZ_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.unibo.participact.domain.proto.DataGyroscopeProtos.internal_static_proto_DataGyroscopeProto_descriptor;
      }

      public it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto getDefaultInstanceForType() {
        return it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.getDefaultInstance();
      }

      public it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto build() {
        it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto buildPartial() {
        it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto result = new it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sampleTime_ = sampleTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rotationX_ = rotationX_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rotationY_ = rotationY_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.rotationZ_ = rotationZ_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto) {
          return mergeFrom((it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto other) {
        if (other == it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto.getDefaultInstance()) return this;
        if (other.hasSampleTime()) {
          setSampleTime(other.getSampleTime());
        }
        if (other.hasRotationX()) {
          setRotationX(other.getRotationX());
        }
        if (other.hasRotationY()) {
          setRotationY(other.getRotationY());
        }
        if (other.hasRotationZ()) {
          setRotationZ(other.getRotationZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSampleTime()) {
          
          return false;
        }
        if (!hasRotationX()) {
          
          return false;
        }
        if (!hasRotationY()) {
          
          return false;
        }
        if (!hasRotationZ()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.unibo.participact.domain.proto.DataGyroscopeProtos.DataGyroscopeProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 sampleTime = 1;
      private long sampleTime_ ;
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public boolean hasSampleTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public long getSampleTime() {
        return sampleTime_;
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public Builder setSampleTime(long value) {
        bitField0_ |= 0x00000001;
        sampleTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public Builder clearSampleTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sampleTime_ = 0L;
        onChanged();
        return this;
      }

      // required float rotation_x = 2;
      private float rotationX_ ;
      /**
       * <code>required float rotation_x = 2;</code>
       */
      public boolean hasRotationX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float rotation_x = 2;</code>
       */
      public float getRotationX() {
        return rotationX_;
      }
      /**
       * <code>required float rotation_x = 2;</code>
       */
      public Builder setRotationX(float value) {
        bitField0_ |= 0x00000002;
        rotationX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float rotation_x = 2;</code>
       */
      public Builder clearRotationX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rotationX_ = 0F;
        onChanged();
        return this;
      }

      // required float rotation_y = 3;
      private float rotationY_ ;
      /**
       * <code>required float rotation_y = 3;</code>
       */
      public boolean hasRotationY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float rotation_y = 3;</code>
       */
      public float getRotationY() {
        return rotationY_;
      }
      /**
       * <code>required float rotation_y = 3;</code>
       */
      public Builder setRotationY(float value) {
        bitField0_ |= 0x00000004;
        rotationY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float rotation_y = 3;</code>
       */
      public Builder clearRotationY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rotationY_ = 0F;
        onChanged();
        return this;
      }

      // required float rotation_z = 4;
      private float rotationZ_ ;
      /**
       * <code>required float rotation_z = 4;</code>
       */
      public boolean hasRotationZ() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float rotation_z = 4;</code>
       */
      public float getRotationZ() {
        return rotationZ_;
      }
      /**
       * <code>required float rotation_z = 4;</code>
       */
      public Builder setRotationZ(float value) {
        bitField0_ |= 0x00000008;
        rotationZ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float rotation_z = 4;</code>
       */
      public Builder clearRotationZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rotationZ_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.DataGyroscopeProto)
    }

    static {
      defaultInstance = new DataGyroscopeProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.DataGyroscopeProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DataGyroscopeProtoList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_DataGyroscopeProtoList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DataGyroscopeProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_DataGyroscopeProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031DataGyroscopeProtos.proto\022\005proto\"A\n\026Da" +
      "taGyroscopeProtoList\022\'\n\004list\030\001 \003(\0132\031.pro" +
      "to.DataGyroscopeProto\"d\n\022DataGyroscopePr" +
      "oto\022\022\n\nsampleTime\030\001 \002(\003\022\022\n\nrotation_x\030\002 " +
      "\002(\002\022\022\n\nrotation_y\030\003 \002(\002\022\022\n\nrotation_z\030\004 " +
      "\002(\002B8\n!it.unibo.participact.domain.proto" +
      "B\023DataGyroscopeProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_DataGyroscopeProtoList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_DataGyroscopeProtoList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_DataGyroscopeProtoList_descriptor,
              new java.lang.String[] { "List", });
          internal_static_proto_DataGyroscopeProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_DataGyroscopeProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_DataGyroscopeProto_descriptor,
              new java.lang.String[] { "SampleTime", "RotationX", "RotationY", "RotationZ", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
