// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataWifiScanProtos.proto

package it.unibo.participact.domain.proto;

public final class DataWifiScanProtos {
  private DataWifiScanProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataWifiScanProtoListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .proto.DataWifiScanProto list = 1;
    /**
     * <code>repeated .proto.DataWifiScanProto list = 1;</code>
     */
    java.util.List<it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto> 
        getListList();
    /**
     * <code>repeated .proto.DataWifiScanProto list = 1;</code>
     */
    it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto getList(int index);
    /**
     * <code>repeated .proto.DataWifiScanProto list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .proto.DataWifiScanProto list = 1;</code>
     */
    java.util.List<? extends it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .proto.DataWifiScanProto list = 1;</code>
     */
    it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.DataWifiScanProtoList}
   */
  public static final class DataWifiScanProtoList extends
      com.google.protobuf.GeneratedMessage
      implements DataWifiScanProtoListOrBuilder {
    // Use DataWifiScanProtoList.newBuilder() to construct.
    private DataWifiScanProtoList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataWifiScanProtoList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataWifiScanProtoList defaultInstance;
    public static DataWifiScanProtoList getDefaultInstance() {
      return defaultInstance;
    }

    public DataWifiScanProtoList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataWifiScanProtoList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(input.readMessage(it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.unibo.participact.domain.proto.DataWifiScanProtos.internal_static_proto_DataWifiScanProtoList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.unibo.participact.domain.proto.DataWifiScanProtos.internal_static_proto_DataWifiScanProtoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList.class, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList.Builder.class);
    }

    public static com.google.protobuf.Parser<DataWifiScanProtoList> PARSER =
        new com.google.protobuf.AbstractParser<DataWifiScanProtoList>() {
      public DataWifiScanProtoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataWifiScanProtoList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataWifiScanProtoList> getParserForType() {
      return PARSER;
    }

    // repeated .proto.DataWifiScanProto list = 1;
    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto> list_;
    /**
     * <code>repeated .proto.DataWifiScanProto list = 1;</code>
     */
    public java.util.List<it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto> getListList() {
      return list_;
    }
    /**
     * <code>repeated .proto.DataWifiScanProto list = 1;</code>
     */
    public java.util.List<? extends it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .proto.DataWifiScanProto list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .proto.DataWifiScanProto list = 1;</code>
     */
    public it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .proto.DataWifiScanProto list = 1;</code>
     */
    public it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private void initFields() {
      list_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getListCount(); i++) {
        if (!getList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DataWifiScanProtoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.unibo.participact.domain.proto.DataWifiScanProtos.internal_static_proto_DataWifiScanProtoList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.unibo.participact.domain.proto.DataWifiScanProtos.internal_static_proto_DataWifiScanProtoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList.class, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList.Builder.class);
      }

      // Construct using it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.unibo.participact.domain.proto.DataWifiScanProtos.internal_static_proto_DataWifiScanProtoList_descriptor;
      }

      public it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList getDefaultInstanceForType() {
        return it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList.getDefaultInstance();
      }

      public it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList build() {
        it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList buildPartial() {
        it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList result = new it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList) {
          return mergeFrom((it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList other) {
        if (other == it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getListCount(); i++) {
          if (!getList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .proto.DataWifiScanProto list = 1;
      private java.util.List<it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.Builder, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoOrBuilder> listBuilder_;

      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public java.util.List<it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public Builder setList(
          int index, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public Builder setList(
          int index, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public Builder addList(it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public Builder addList(
          int index, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public Builder addList(
          it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public Builder addList(
          int index, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          super.addAll(values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public java.util.List<? extends it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.DataWifiScanProto list = 1;</code>
       */
      public java.util.List<it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.Builder, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.Builder, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.DataWifiScanProtoList)
    }

    static {
      defaultInstance = new DataWifiScanProtoList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.DataWifiScanProtoList)
  }

  public interface DataWifiScanProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 sampleTime = 1;
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    boolean hasSampleTime();
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    long getSampleTime();

    // required string bssid = 2;
    /**
     * <code>required string bssid = 2;</code>
     */
    boolean hasBssid();
    /**
     * <code>required string bssid = 2;</code>
     */
    java.lang.String getBssid();
    /**
     * <code>required string bssid = 2;</code>
     */
    com.google.protobuf.ByteString
        getBssidBytes();

    // required string ssid = 3;
    /**
     * <code>required string ssid = 3;</code>
     */
    boolean hasSsid();
    /**
     * <code>required string ssid = 3;</code>
     */
    java.lang.String getSsid();
    /**
     * <code>required string ssid = 3;</code>
     */
    com.google.protobuf.ByteString
        getSsidBytes();

    // required string capabilities = 4;
    /**
     * <code>required string capabilities = 4;</code>
     */
    boolean hasCapabilities();
    /**
     * <code>required string capabilities = 4;</code>
     */
    java.lang.String getCapabilities();
    /**
     * <code>required string capabilities = 4;</code>
     */
    com.google.protobuf.ByteString
        getCapabilitiesBytes();

    // required int32 frequency = 5;
    /**
     * <code>required int32 frequency = 5;</code>
     */
    boolean hasFrequency();
    /**
     * <code>required int32 frequency = 5;</code>
     */
    int getFrequency();

    // required int32 level = 6;
    /**
     * <code>required int32 level = 6;</code>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 6;</code>
     */
    int getLevel();
  }
  /**
   * Protobuf type {@code proto.DataWifiScanProto}
   */
  public static final class DataWifiScanProto extends
      com.google.protobuf.GeneratedMessage
      implements DataWifiScanProtoOrBuilder {
    // Use DataWifiScanProto.newBuilder() to construct.
    private DataWifiScanProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataWifiScanProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataWifiScanProto defaultInstance;
    public static DataWifiScanProto getDefaultInstance() {
      return defaultInstance;
    }

    public DataWifiScanProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataWifiScanProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sampleTime_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              bssid_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              ssid_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              capabilities_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              frequency_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              level_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.unibo.participact.domain.proto.DataWifiScanProtos.internal_static_proto_DataWifiScanProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.unibo.participact.domain.proto.DataWifiScanProtos.internal_static_proto_DataWifiScanProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.class, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.Builder.class);
    }

    public static com.google.protobuf.Parser<DataWifiScanProto> PARSER =
        new com.google.protobuf.AbstractParser<DataWifiScanProto>() {
      public DataWifiScanProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataWifiScanProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataWifiScanProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 sampleTime = 1;
    public static final int SAMPLETIME_FIELD_NUMBER = 1;
    private long sampleTime_;
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    public boolean hasSampleTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    public long getSampleTime() {
      return sampleTime_;
    }

    // required string bssid = 2;
    public static final int BSSID_FIELD_NUMBER = 2;
    private java.lang.Object bssid_;
    /**
     * <code>required string bssid = 2;</code>
     */
    public boolean hasBssid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string bssid = 2;</code>
     */
    public java.lang.String getBssid() {
      java.lang.Object ref = bssid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bssid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string bssid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBssidBytes() {
      java.lang.Object ref = bssid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bssid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string ssid = 3;
    public static final int SSID_FIELD_NUMBER = 3;
    private java.lang.Object ssid_;
    /**
     * <code>required string ssid = 3;</code>
     */
    public boolean hasSsid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string ssid = 3;</code>
     */
    public java.lang.String getSsid() {
      java.lang.Object ref = ssid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ssid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ssid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSsidBytes() {
      java.lang.Object ref = ssid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ssid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string capabilities = 4;
    public static final int CAPABILITIES_FIELD_NUMBER = 4;
    private java.lang.Object capabilities_;
    /**
     * <code>required string capabilities = 4;</code>
     */
    public boolean hasCapabilities() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string capabilities = 4;</code>
     */
    public java.lang.String getCapabilities() {
      java.lang.Object ref = capabilities_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          capabilities_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string capabilities = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCapabilitiesBytes() {
      java.lang.Object ref = capabilities_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        capabilities_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 frequency = 5;
    public static final int FREQUENCY_FIELD_NUMBER = 5;
    private int frequency_;
    /**
     * <code>required int32 frequency = 5;</code>
     */
    public boolean hasFrequency() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 frequency = 5;</code>
     */
    public int getFrequency() {
      return frequency_;
    }

    // required int32 level = 6;
    public static final int LEVEL_FIELD_NUMBER = 6;
    private int level_;
    /**
     * <code>required int32 level = 6;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 level = 6;</code>
     */
    public int getLevel() {
      return level_;
    }

    private void initFields() {
      sampleTime_ = 0L;
      bssid_ = "";
      ssid_ = "";
      capabilities_ = "";
      frequency_ = 0;
      level_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSampleTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBssid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSsid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCapabilities()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFrequency()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, sampleTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBssidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSsidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCapabilitiesBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, frequency_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, level_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sampleTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBssidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSsidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCapabilitiesBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, frequency_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, level_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DataWifiScanProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.unibo.participact.domain.proto.DataWifiScanProtos.internal_static_proto_DataWifiScanProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.unibo.participact.domain.proto.DataWifiScanProtos.internal_static_proto_DataWifiScanProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.class, it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.Builder.class);
      }

      // Construct using it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sampleTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        bssid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ssid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        capabilities_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        frequency_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.unibo.participact.domain.proto.DataWifiScanProtos.internal_static_proto_DataWifiScanProto_descriptor;
      }

      public it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto getDefaultInstanceForType() {
        return it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.getDefaultInstance();
      }

      public it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto build() {
        it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto buildPartial() {
        it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto result = new it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sampleTime_ = sampleTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bssid_ = bssid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ssid_ = ssid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.capabilities_ = capabilities_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.frequency_ = frequency_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.level_ = level_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto) {
          return mergeFrom((it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto other) {
        if (other == it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto.getDefaultInstance()) return this;
        if (other.hasSampleTime()) {
          setSampleTime(other.getSampleTime());
        }
        if (other.hasBssid()) {
          bitField0_ |= 0x00000002;
          bssid_ = other.bssid_;
          onChanged();
        }
        if (other.hasSsid()) {
          bitField0_ |= 0x00000004;
          ssid_ = other.ssid_;
          onChanged();
        }
        if (other.hasCapabilities()) {
          bitField0_ |= 0x00000008;
          capabilities_ = other.capabilities_;
          onChanged();
        }
        if (other.hasFrequency()) {
          setFrequency(other.getFrequency());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSampleTime()) {
          
          return false;
        }
        if (!hasBssid()) {
          
          return false;
        }
        if (!hasSsid()) {
          
          return false;
        }
        if (!hasCapabilities()) {
          
          return false;
        }
        if (!hasFrequency()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.unibo.participact.domain.proto.DataWifiScanProtos.DataWifiScanProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 sampleTime = 1;
      private long sampleTime_ ;
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public boolean hasSampleTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public long getSampleTime() {
        return sampleTime_;
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public Builder setSampleTime(long value) {
        bitField0_ |= 0x00000001;
        sampleTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public Builder clearSampleTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sampleTime_ = 0L;
        onChanged();
        return this;
      }

      // required string bssid = 2;
      private java.lang.Object bssid_ = "";
      /**
       * <code>required string bssid = 2;</code>
       */
      public boolean hasBssid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string bssid = 2;</code>
       */
      public java.lang.String getBssid() {
        java.lang.Object ref = bssid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          bssid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string bssid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBssidBytes() {
        java.lang.Object ref = bssid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bssid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string bssid = 2;</code>
       */
      public Builder setBssid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bssid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string bssid = 2;</code>
       */
      public Builder clearBssid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bssid_ = getDefaultInstance().getBssid();
        onChanged();
        return this;
      }
      /**
       * <code>required string bssid = 2;</code>
       */
      public Builder setBssidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bssid_ = value;
        onChanged();
        return this;
      }

      // required string ssid = 3;
      private java.lang.Object ssid_ = "";
      /**
       * <code>required string ssid = 3;</code>
       */
      public boolean hasSsid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string ssid = 3;</code>
       */
      public java.lang.String getSsid() {
        java.lang.Object ref = ssid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ssid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ssid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSsidBytes() {
        java.lang.Object ref = ssid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ssid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ssid = 3;</code>
       */
      public Builder setSsid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ssid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ssid = 3;</code>
       */
      public Builder clearSsid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ssid_ = getDefaultInstance().getSsid();
        onChanged();
        return this;
      }
      /**
       * <code>required string ssid = 3;</code>
       */
      public Builder setSsidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ssid_ = value;
        onChanged();
        return this;
      }

      // required string capabilities = 4;
      private java.lang.Object capabilities_ = "";
      /**
       * <code>required string capabilities = 4;</code>
       */
      public boolean hasCapabilities() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string capabilities = 4;</code>
       */
      public java.lang.String getCapabilities() {
        java.lang.Object ref = capabilities_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          capabilities_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string capabilities = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCapabilitiesBytes() {
        java.lang.Object ref = capabilities_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          capabilities_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string capabilities = 4;</code>
       */
      public Builder setCapabilities(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        capabilities_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string capabilities = 4;</code>
       */
      public Builder clearCapabilities() {
        bitField0_ = (bitField0_ & ~0x00000008);
        capabilities_ = getDefaultInstance().getCapabilities();
        onChanged();
        return this;
      }
      /**
       * <code>required string capabilities = 4;</code>
       */
      public Builder setCapabilitiesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        capabilities_ = value;
        onChanged();
        return this;
      }

      // required int32 frequency = 5;
      private int frequency_ ;
      /**
       * <code>required int32 frequency = 5;</code>
       */
      public boolean hasFrequency() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 frequency = 5;</code>
       */
      public int getFrequency() {
        return frequency_;
      }
      /**
       * <code>required int32 frequency = 5;</code>
       */
      public Builder setFrequency(int value) {
        bitField0_ |= 0x00000010;
        frequency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 frequency = 5;</code>
       */
      public Builder clearFrequency() {
        bitField0_ = (bitField0_ & ~0x00000010);
        frequency_ = 0;
        onChanged();
        return this;
      }

      // required int32 level = 6;
      private int level_ ;
      /**
       * <code>required int32 level = 6;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 level = 6;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 6;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000020;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 6;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        level_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.DataWifiScanProto)
    }

    static {
      defaultInstance = new DataWifiScanProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.DataWifiScanProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DataWifiScanProtoList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_DataWifiScanProtoList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DataWifiScanProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_DataWifiScanProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030DataWifiScanProtos.proto\022\005proto\"?\n\025Dat" +
      "aWifiScanProtoList\022&\n\004list\030\001 \003(\0132\030.proto" +
      ".DataWifiScanProto\"|\n\021DataWifiScanProto\022" +
      "\022\n\nsampleTime\030\001 \002(\003\022\r\n\005bssid\030\002 \002(\t\022\014\n\004ss" +
      "id\030\003 \002(\t\022\024\n\014capabilities\030\004 \002(\t\022\021\n\tfreque" +
      "ncy\030\005 \002(\005\022\r\n\005level\030\006 \002(\005B7\n!it.unibo.par" +
      "ticipact.domain.protoB\022DataWifiScanProto" +
      "s"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_DataWifiScanProtoList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_DataWifiScanProtoList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_DataWifiScanProtoList_descriptor,
              new java.lang.String[] { "List", });
          internal_static_proto_DataWifiScanProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_DataWifiScanProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_DataWifiScanProto_descriptor,
              new java.lang.String[] { "SampleTime", "Bssid", "Ssid", "Capabilities", "Frequency", "Level", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
