// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataPhoneCallDurationProtos.proto

package it.unibo.participact.domain.proto;

public final class DataPhoneCallDurationProtos {
  private DataPhoneCallDurationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataPhoneCallDurationProtoListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .proto.DataPhoneCallDurationProto list = 1;
    /**
     * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
     */
    java.util.List<it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto> 
        getListList();
    /**
     * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
     */
    it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto getList(int index);
    /**
     * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
     */
    java.util.List<? extends it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
     */
    it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.DataPhoneCallDurationProtoList}
   */
  public static final class DataPhoneCallDurationProtoList extends
      com.google.protobuf.GeneratedMessage
      implements DataPhoneCallDurationProtoListOrBuilder {
    // Use DataPhoneCallDurationProtoList.newBuilder() to construct.
    private DataPhoneCallDurationProtoList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataPhoneCallDurationProtoList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataPhoneCallDurationProtoList defaultInstance;
    public static DataPhoneCallDurationProtoList getDefaultInstance() {
      return defaultInstance;
    }

    public DataPhoneCallDurationProtoList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataPhoneCallDurationProtoList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(input.readMessage(it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.internal_static_proto_DataPhoneCallDurationProtoList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.internal_static_proto_DataPhoneCallDurationProtoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList.class, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList.Builder.class);
    }

    public static com.google.protobuf.Parser<DataPhoneCallDurationProtoList> PARSER =
        new com.google.protobuf.AbstractParser<DataPhoneCallDurationProtoList>() {
      public DataPhoneCallDurationProtoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataPhoneCallDurationProtoList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataPhoneCallDurationProtoList> getParserForType() {
      return PARSER;
    }

    // repeated .proto.DataPhoneCallDurationProto list = 1;
    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto> list_;
    /**
     * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
     */
    public java.util.List<it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto> getListList() {
      return list_;
    }
    /**
     * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
     */
    public java.util.List<? extends it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
     */
    public it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
     */
    public it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private void initFields() {
      list_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getListCount(); i++) {
        if (!getList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DataPhoneCallDurationProtoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.internal_static_proto_DataPhoneCallDurationProtoList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.internal_static_proto_DataPhoneCallDurationProtoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList.class, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList.Builder.class);
      }

      // Construct using it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.internal_static_proto_DataPhoneCallDurationProtoList_descriptor;
      }

      public it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList getDefaultInstanceForType() {
        return it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList.getDefaultInstance();
      }

      public it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList build() {
        it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList buildPartial() {
        it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList result = new it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList) {
          return mergeFrom((it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList other) {
        if (other == it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getListCount(); i++) {
          if (!getList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .proto.DataPhoneCallDurationProto list = 1;
      private java.util.List<it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.Builder, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoOrBuilder> listBuilder_;

      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public java.util.List<it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public Builder setList(
          int index, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public Builder setList(
          int index, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public Builder addList(it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public Builder addList(
          int index, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public Builder addList(
          it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public Builder addList(
          int index, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          super.addAll(values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public java.util.List<? extends it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.DataPhoneCallDurationProto list = 1;</code>
       */
      public java.util.List<it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.Builder, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.Builder, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.DataPhoneCallDurationProtoList)
    }

    static {
      defaultInstance = new DataPhoneCallDurationProtoList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.DataPhoneCallDurationProtoList)
  }

  public interface DataPhoneCallDurationProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 sampleTime = 1;
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    boolean hasSampleTime();
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    long getSampleTime();

    // required int64 call_start = 2;
    /**
     * <code>required int64 call_start = 2;</code>
     */
    boolean hasCallStart();
    /**
     * <code>required int64 call_start = 2;</code>
     */
    long getCallStart();

    // required int64 call_end = 3;
    /**
     * <code>required int64 call_end = 3;</code>
     */
    boolean hasCallEnd();
    /**
     * <code>required int64 call_end = 3;</code>
     */
    long getCallEnd();

    // required bool is_incoming = 4;
    /**
     * <code>required bool is_incoming = 4;</code>
     */
    boolean hasIsIncoming();
    /**
     * <code>required bool is_incoming = 4;</code>
     */
    boolean getIsIncoming();

    // required string phone_number = 5;
    /**
     * <code>required string phone_number = 5;</code>
     */
    boolean hasPhoneNumber();
    /**
     * <code>required string phone_number = 5;</code>
     */
    java.lang.String getPhoneNumber();
    /**
     * <code>required string phone_number = 5;</code>
     */
    com.google.protobuf.ByteString
        getPhoneNumberBytes();
  }
  /**
   * Protobuf type {@code proto.DataPhoneCallDurationProto}
   */
  public static final class DataPhoneCallDurationProto extends
      com.google.protobuf.GeneratedMessage
      implements DataPhoneCallDurationProtoOrBuilder {
    // Use DataPhoneCallDurationProto.newBuilder() to construct.
    private DataPhoneCallDurationProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataPhoneCallDurationProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataPhoneCallDurationProto defaultInstance;
    public static DataPhoneCallDurationProto getDefaultInstance() {
      return defaultInstance;
    }

    public DataPhoneCallDurationProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataPhoneCallDurationProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sampleTime_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              callStart_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              callEnd_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isIncoming_ = input.readBool();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              phoneNumber_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.internal_static_proto_DataPhoneCallDurationProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.internal_static_proto_DataPhoneCallDurationProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.class, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.Builder.class);
    }

    public static com.google.protobuf.Parser<DataPhoneCallDurationProto> PARSER =
        new com.google.protobuf.AbstractParser<DataPhoneCallDurationProto>() {
      public DataPhoneCallDurationProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataPhoneCallDurationProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataPhoneCallDurationProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 sampleTime = 1;
    public static final int SAMPLETIME_FIELD_NUMBER = 1;
    private long sampleTime_;
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    public boolean hasSampleTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 sampleTime = 1;</code>
     */
    public long getSampleTime() {
      return sampleTime_;
    }

    // required int64 call_start = 2;
    public static final int CALL_START_FIELD_NUMBER = 2;
    private long callStart_;
    /**
     * <code>required int64 call_start = 2;</code>
     */
    public boolean hasCallStart() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 call_start = 2;</code>
     */
    public long getCallStart() {
      return callStart_;
    }

    // required int64 call_end = 3;
    public static final int CALL_END_FIELD_NUMBER = 3;
    private long callEnd_;
    /**
     * <code>required int64 call_end = 3;</code>
     */
    public boolean hasCallEnd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 call_end = 3;</code>
     */
    public long getCallEnd() {
      return callEnd_;
    }

    // required bool is_incoming = 4;
    public static final int IS_INCOMING_FIELD_NUMBER = 4;
    private boolean isIncoming_;
    /**
     * <code>required bool is_incoming = 4;</code>
     */
    public boolean hasIsIncoming() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool is_incoming = 4;</code>
     */
    public boolean getIsIncoming() {
      return isIncoming_;
    }

    // required string phone_number = 5;
    public static final int PHONE_NUMBER_FIELD_NUMBER = 5;
    private java.lang.Object phoneNumber_;
    /**
     * <code>required string phone_number = 5;</code>
     */
    public boolean hasPhoneNumber() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string phone_number = 5;</code>
     */
    public java.lang.String getPhoneNumber() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phoneNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string phone_number = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sampleTime_ = 0L;
      callStart_ = 0L;
      callEnd_ = 0L;
      isIncoming_ = false;
      phoneNumber_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSampleTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCallStart()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCallEnd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsIncoming()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhoneNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, sampleTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, callStart_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, callEnd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isIncoming_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPhoneNumberBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sampleTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, callStart_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, callEnd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isIncoming_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPhoneNumberBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DataPhoneCallDurationProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.internal_static_proto_DataPhoneCallDurationProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.internal_static_proto_DataPhoneCallDurationProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.class, it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.Builder.class);
      }

      // Construct using it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sampleTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        callStart_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        callEnd_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        isIncoming_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        phoneNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.internal_static_proto_DataPhoneCallDurationProto_descriptor;
      }

      public it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto getDefaultInstanceForType() {
        return it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.getDefaultInstance();
      }

      public it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto build() {
        it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto buildPartial() {
        it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto result = new it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sampleTime_ = sampleTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.callStart_ = callStart_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.callEnd_ = callEnd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isIncoming_ = isIncoming_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.phoneNumber_ = phoneNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto) {
          return mergeFrom((it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto other) {
        if (other == it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto.getDefaultInstance()) return this;
        if (other.hasSampleTime()) {
          setSampleTime(other.getSampleTime());
        }
        if (other.hasCallStart()) {
          setCallStart(other.getCallStart());
        }
        if (other.hasCallEnd()) {
          setCallEnd(other.getCallEnd());
        }
        if (other.hasIsIncoming()) {
          setIsIncoming(other.getIsIncoming());
        }
        if (other.hasPhoneNumber()) {
          bitField0_ |= 0x00000010;
          phoneNumber_ = other.phoneNumber_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSampleTime()) {
          
          return false;
        }
        if (!hasCallStart()) {
          
          return false;
        }
        if (!hasCallEnd()) {
          
          return false;
        }
        if (!hasIsIncoming()) {
          
          return false;
        }
        if (!hasPhoneNumber()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.unibo.participact.domain.proto.DataPhoneCallDurationProtos.DataPhoneCallDurationProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 sampleTime = 1;
      private long sampleTime_ ;
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public boolean hasSampleTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public long getSampleTime() {
        return sampleTime_;
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public Builder setSampleTime(long value) {
        bitField0_ |= 0x00000001;
        sampleTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sampleTime = 1;</code>
       */
      public Builder clearSampleTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sampleTime_ = 0L;
        onChanged();
        return this;
      }

      // required int64 call_start = 2;
      private long callStart_ ;
      /**
       * <code>required int64 call_start = 2;</code>
       */
      public boolean hasCallStart() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 call_start = 2;</code>
       */
      public long getCallStart() {
        return callStart_;
      }
      /**
       * <code>required int64 call_start = 2;</code>
       */
      public Builder setCallStart(long value) {
        bitField0_ |= 0x00000002;
        callStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 call_start = 2;</code>
       */
      public Builder clearCallStart() {
        bitField0_ = (bitField0_ & ~0x00000002);
        callStart_ = 0L;
        onChanged();
        return this;
      }

      // required int64 call_end = 3;
      private long callEnd_ ;
      /**
       * <code>required int64 call_end = 3;</code>
       */
      public boolean hasCallEnd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 call_end = 3;</code>
       */
      public long getCallEnd() {
        return callEnd_;
      }
      /**
       * <code>required int64 call_end = 3;</code>
       */
      public Builder setCallEnd(long value) {
        bitField0_ |= 0x00000004;
        callEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 call_end = 3;</code>
       */
      public Builder clearCallEnd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        callEnd_ = 0L;
        onChanged();
        return this;
      }

      // required bool is_incoming = 4;
      private boolean isIncoming_ ;
      /**
       * <code>required bool is_incoming = 4;</code>
       */
      public boolean hasIsIncoming() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool is_incoming = 4;</code>
       */
      public boolean getIsIncoming() {
        return isIncoming_;
      }
      /**
       * <code>required bool is_incoming = 4;</code>
       */
      public Builder setIsIncoming(boolean value) {
        bitField0_ |= 0x00000008;
        isIncoming_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool is_incoming = 4;</code>
       */
      public Builder clearIsIncoming() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isIncoming_ = false;
        onChanged();
        return this;
      }

      // required string phone_number = 5;
      private java.lang.Object phoneNumber_ = "";
      /**
       * <code>required string phone_number = 5;</code>
       */
      public boolean hasPhoneNumber() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string phone_number = 5;</code>
       */
      public java.lang.String getPhoneNumber() {
        java.lang.Object ref = phoneNumber_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          phoneNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string phone_number = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string phone_number = 5;</code>
       */
      public Builder setPhoneNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string phone_number = 5;</code>
       */
      public Builder clearPhoneNumber() {
        bitField0_ = (bitField0_ & ~0x00000010);
        phoneNumber_ = getDefaultInstance().getPhoneNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required string phone_number = 5;</code>
       */
      public Builder setPhoneNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        phoneNumber_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.DataPhoneCallDurationProto)
    }

    static {
      defaultInstance = new DataPhoneCallDurationProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.DataPhoneCallDurationProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DataPhoneCallDurationProtoList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_DataPhoneCallDurationProtoList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DataPhoneCallDurationProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_DataPhoneCallDurationProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!DataPhoneCallDurationProtos.proto\022\005pro" +
      "to\"Q\n\036DataPhoneCallDurationProtoList\022/\n\004" +
      "list\030\001 \003(\0132!.proto.DataPhoneCallDuration" +
      "Proto\"\201\001\n\032DataPhoneCallDurationProto\022\022\n\n" +
      "sampleTime\030\001 \002(\003\022\022\n\ncall_start\030\002 \002(\003\022\020\n\010" +
      "call_end\030\003 \002(\003\022\023\n\013is_incoming\030\004 \002(\010\022\024\n\014p" +
      "hone_number\030\005 \002(\tB@\n!it.unibo.participac" +
      "t.domain.protoB\033DataPhoneCallDurationPro" +
      "tos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_DataPhoneCallDurationProtoList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_DataPhoneCallDurationProtoList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_DataPhoneCallDurationProtoList_descriptor,
              new java.lang.String[] { "List", });
          internal_static_proto_DataPhoneCallDurationProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_DataPhoneCallDurationProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_DataPhoneCallDurationProto_descriptor,
              new java.lang.String[] { "SampleTime", "CallStart", "CallEnd", "IsIncoming", "PhoneNumber", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
