package it.unibo.paserver.domain;

/**
 * Nao alterar ordem do enum, pois influencia nas credencias e permissoes
 *
 * @author Claudio
 */
public enum Role {
    ROLE_ADMIN, ROLE_USER, ROLE_VIEW, ROLE_RESEARCHER_FIRST, ROLE_RESEARCHER_SECOND, NOT_ALLOWED_ACCESS, ROLE_COOPERATION_AGREEMENT, ROLE_RESEARCHER_OMBUDSMAN, ROLE_RESEARCHER_OMBUDSMAN_CONSULTANT, ROLE_RESEARCHER_OMBUDSMAN_COLLABORATOR, ROLE_RESEARCHER_OMBUDSMAN_EDITOR;
}
