package it.unibo.paserver.domain;

public enum TaskState {
	AVAILABLE, ACCEPTED, RUNNING, REJECTED, FAILED, INTERRUPTED, ERROR, UNKNOWN, SUSPENDED, ANY, COMPLETED_NOT_SYNC_WITH_SERVER, COMPLETED_WITH_SUCCESS, COMPLETED_WITH_FAILURE, IGNORED, NONE;
}
